#@data/values

#@overlay/match-child-defaults missing_ok=True
---
tap:
  devNamespace: tap-dev

  domains:
    learningCenter: learningcenter.jkcloudmesh.com
    knative: apps.jkcloudmesh.com

domain: jkcloudmesh.com
tls:
  secretName: tls
  namespace: tanzu-system-ingress